language: node_js
node_js:
  - "5"
script:
  - brunch b
  - karma start karma.conf.js --single-run
  - cat ./coverage/Pha*/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  email:
    - argshook@gmail.com
